Write a blog on upgrading to elm 0.19
EdutainmentLIVE/edutainmentlive.github.io pull request #15
Opened 2019-02-27 15:35 UTC by saralich

Story details: https://app.clubhouse.io/itprotv/story/17873

Hoping for some feedback :-) still need to expand on the "what we like" and would love some suggestions

2019-02-27 18:47 UTC, tillydray submitted a review, later dismissed
Some mostly grammatical and phrasing changes.

2019-02-27 18:47 UTC, tillydray commented on _posts/Upgrading_Elm.md
> +## What Didn't Go Well For Us
I thought of another one: their debugger no longer works in 0.19. That's not about upgrading to 0.19, it's about being on 0.19, so maybe it's not in scope for this post idk.

2019-02-27 18:47 UTC, tillydray commented on _posts/Upgrading_Elm.md
> +[Elm](https://elm-lang.org/) is a front-end, functional language that compiles into JavaScript for seamless web development. When I started at ITProTV, we were using Elm 0.18 for one of our apps. As
```suggestion
[Elm](https://elm-lang.org/) is a front-end, functional language that compiles to JavaScript for seamless web development, and we love it. It's been around for years and in August of 2018 it upgraded to version 0.19. We didn't get around to upgrading our app to 0.19 until January of 2019. This is our experience.

The creator of Elm released [this upgrade guide](https://github.com/elm/compiler/blob/a968e817e65d30493c344ac96c9c904b19a7f038/upgrade-docs/0.19.md) as well as [this document about what changed](https://elm-lang.org/blog/small-assets-without-the-headache), both were helpful but neither was an end-all answer. In this post, we will go over what didn't go well for us, changes we as a team would suggest, and the wonderful things about Elm 0.19 that make this upgrade worth the potential struggle.
```

2019-02-27 18:47 UTC, JasonMFry commented on _posts/Upgrading_Elm.md
> +1.  The old documentation became tough to find - the 0.19 documents replaced 0.18 on elm-lang, and after some digging, we were able to find a Github site that contained the 0.18 docs. It was good the
```suggestion
1.  The old documentation became tough to find - the 0.19 documents replaced 0.18 on elm-lang, and after some digging we were able to find a Github site that contained the 0.18 docs, but then that went away and it was some time before we discovered their (hopefully permanent) location [here](https://dmy.github.io/elm-0.18-packages/). It was good they were somewhere, but some link between 0.19 and 0.18 would have been helpful.
```

2019-02-27 18:47 UTC, JasonMFry commented on _posts/Upgrading_Elm.md
> +1. As noted, having a working compiler, especially elm's friendly compiler, makes working through kinks much easier. With 0.19, the compiler and packages have to be upgraded simultaneously. If these
```suggestion
1. As noted, having a working compiler, especially elm's friendly compiler, makes working through kinks much easier. With 0.19, the compiler and packages have to be upgraded simultaneously. If these were separate, allowing for one to be upgraded at a time, the upgrade process would be much smoother in both scenarios.
```

2019-02-27 18:47 UTC, JasonMFry commented on _posts/Upgrading_Elm.md
> +1. Make previous version documentation easier to find and make it easier to compare to new version, in case type signatures change. A lot of the documentation available for other languages allows a u
```suggestion
1. Make previous versions' documentation easier to find, and make it easier to compare with the new version. This is super helpful when type signatures change. A lot of the documentation available for other languages allows a user to select versions to look at in order to compare between versions.
```

2019-02-28 15:24 UTC, tfausak approved these changes

2019-02-28 16:34 UTC, saralich commented
Did a few fixes to make some of the language more positive and update the author - I don't feel comfortable being the only one listed, as this is mostly not my writing, so I put the team.

2019-02-28 21:34 UTC, tillydray approved these changes

2019-02-28 22:02 UTC, tillydray requested changes
We should change the name of the file before posting.

2019-03-01 14:18 UTC, tillydray approved these changes

2019-03-01 14:50 UTC, Xandrak approved these changes
Lookin' good!

2019-03-01 18:56 UTC, merged