Adds rough outline for blog post (don't merge yet)
EdutainmentLIVE/edutainmentlive.github.io pull request #9
Opened 2018-11-13 22:04 UTC by JasonMFry

Just making a PR to get some discussion, everyone feel free to add to this as you want.

2018-11-14 15:37 UTC, tfausak commented
Looks good to me so far!

2018-12-06 17:02 UTC, tfausak approved these changes
👨‍👨‍👧‍👦

2018-12-07 18:29 UTC, gera-cameron requested changes
Just a few things. Made suggestions for all of them though, I think.

2018-12-07 18:29 UTC, gera-cameron commented on _posts/2018-11-27-our-first-experiment-with-promiscuous-pairing-is-a-success.md
> +the Jedi (they were on the story during the previous block) and the other was the padawn. When
```suggestion
the Jedi (they were on the story during the previous block) and the other was the Padawan. When
```

2018-12-07 18:29 UTC, gera-cameron commented on _posts/2018-11-27-our-first-experiment-with-promiscuous-pairing-is-a-success.md
> +the next padawn. The padawn drove on their own machine (with few exceptions) while the Jedi
```suggestion
the next Padawan. The Padawan drove on their own machine (with few exceptions) while the Jedi
```

2018-12-07 18:29 UTC, gera-cameron commented on _posts/2018-11-27-our-first-experiment-with-promiscuous-pairing-is-a-success.md
> +the Jedi couldn't answer the padawn's questions, and since we weren't used to this experience we
```suggestion
the Jedi couldn't answer the Padawan's questions, and since we weren't used to this experience we
```

2018-12-07 18:29 UTC, gera-cameron commented on _posts/2018-11-27-our-first-experiment-with-promiscuous-pairing-is-a-success.md
> +todo lists which made it much easier to onboard a padawn. In fact, we were able to get our
```suggestion
todo lists which made it much easier to onboard a Padawan. In fact, we were able to get our
```

2018-12-07 20:37 UTC, merged